package view;

import dao.AppointmentDAO;
import dao.BillDAO;
import dao.UsedServiceDAO;
import model.Bill;
import model.UsedService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class BillDetailFrm extends JFrame {
    private JPanel mainPanel;
    private JTextField ngàyThanhToánTextField;
    private JTextField sốĐiệnThoạiTextField;
    private JTable tblUsedServiceList;
    private JTextField phươngThứcThanhToánTextField;
    private JTextField txtClientPhone;
    private JTextField txtClientName;
    private JTextField txtPaymentDate;
    private JTextField họTênTextField;
    private JButton btnCancelBill;
    private JButton btnClose;
    private JTextField txtTotalAmount;
    private JTextField tổngTiềnTextField;
    private JTextArea txtNote;
    private JTextField txtPaymentMethod;

    private DefaultTableModel tableModel;
    private int curBillId;

    public BillDetailFrm(int billId) {
        this.curBillId = billId;

        setTitle("Chi tiết Hóa Đơn - Hủy Hóa Đơn");
        setContentPane(mainPanel);
        setSize(800, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        txtClientName.setEditable(false);
        txtClientPhone.setEditable(false);
        txtPaymentDate.setEditable(false);
        txtTotalAmount.setEditable(false); // không thể sửa

        ngàyThanhToánTextField.setEditable(false);
        họTênTextField.setEditable(false);
        sốĐiệnThoạiTextField.setEditable(false);
        phươngThứcThanhToánTextField.setEditable(false);
        tổngTiềnTextField.setEditable(false);

        setupTable();
        loadData();

        btnCancelBill.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String note = txtNote.getText().trim();
                if (note.isEmpty()) {
                    JOptionPane.showMessageDialog(BillDetailFrm.this, "Vui lòng nhập lý do hủy hóa đơn vào ô Ghi chú!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                int confirm = JOptionPane.showConfirmDialog(BillDetailFrm.this,
                        "Bạn có chắc chắn muốn hủy hóa đơn này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    BillDAO billDAO = new BillDAO();
                    boolean isCancel = billDAO.cancelBill(curBillId, note);

                    if (isCancel) {
                        AppointmentDAO appointmentDAO = new AppointmentDAO();
                        ArrayList<Integer> appointmentIds = appointmentDAO.getAppointmentIdsById(curBillId);
                        appointmentDAO.updateStatus(appointmentIds, curBillId, "Pending");

                        JOptionPane.showMessageDialog(BillDetailFrm.this, "Hủy hóa đơn thành công!");
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(BillDetailFrm.this, "Lỗi khi hủy hóa đơn!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
        btnClose.addActionListener(e -> dispose());
    }

    private void setupTable() {
        String[] cols = {"STT", "Tên dịch vụ", "Số lượng", "Đơn giá", "Thành tiền"};
        tableModel = new DefaultTableModel(cols, 0);
        tblUsedServiceList.setModel(tableModel);
    }

    private void loadData() {
        BillDAO billDAO = new BillDAO();
        Bill bill = billDAO.getBillDetail(curBillId);

        if (bill != null) {
            txtClientName.setText(bill.getClientName());
            txtClientPhone.setText(bill.getClientPhone());
            txtPaymentDate.setText(bill.getPaymentDate().toString());
            txtPaymentMethod.setText(bill.getPaymentMethod());
            txtTotalAmount.setText(String.format("%,.0f VNĐ", bill.getPaymentAmount()));
        }

        AppointmentDAO appointmentDAO = new AppointmentDAO();
        ArrayList<Integer> appointmentIds = appointmentDAO.getAppointmentIdsById(curBillId);

        UsedServiceDAO usedServiceDAO = new UsedServiceDAO();
        ArrayList<UsedService> usedServices = usedServiceDAO.getUsedServicesByAppointmentIds(appointmentIds);

        int index = 1;
        for (UsedService usedService : usedServices) {
            tableModel.addRow(new Object[]{
                    index++,
                    usedService.getServiceName(),
                    usedService.getQuantity(),
                    String.format("%,.0f", usedService.getPrice()),
                    String.format("%,.0f", usedService.getTotalAmount())
            });
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(8, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(mainPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ngàyThanhToánTextField = new JTextField();
        ngàyThanhToánTextField.setText("Ngày thanh toán");
        mainPanel.add(ngàyThanhToánTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        sốĐiệnThoạiTextField = new JTextField();
        sốĐiệnThoạiTextField.setText("Số điện thoại");
        mainPanel.add(sốĐiệnThoạiTextField, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tblUsedServiceList = new JTable();
        scrollPane1.setViewportView(tblUsedServiceList);
        phươngThứcThanhToánTextField = new JTextField();
        phươngThứcThanhToánTextField.setText("Phương thức thanh toán");
        mainPanel.add(phươngThứcThanhToánTextField, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtClientPhone = new JTextField();
        mainPanel.add(txtClientPhone, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtClientName = new JTextField();
        mainPanel.add(txtClientName, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtPaymentDate = new JTextField();
        mainPanel.add(txtPaymentDate, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        họTênTextField = new JTextField();
        họTênTextField.setText("Họ tên");
        mainPanel.add(họTênTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnCancelBill = new JButton();
        btnCancelBill.setText("Confirm");
        mainPanel.add(btnCancelBill, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnClose = new JButton();
        btnClose.setText("Cancel");
        mainPanel.add(btnClose, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtTotalAmount = new JTextField();
        mainPanel.add(txtTotalAmount, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tổngTiềnTextField = new JTextField();
        tổngTiềnTextField.setText("Tổng tiền");
        mainPanel.add(tổngTiềnTextField, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtNote = new JTextArea();
        txtNote.setText("Note:");
        mainPanel.add(txtNote, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        txtPaymentMethod = new JTextField();
        mainPanel.add(txtPaymentMethod, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }
}
