package view;

import dao.AppointmentDAO;
import dao.BillDAO;
import dao.UsedServiceDAO;
import model.Bill;
import model.UsedService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.sql.Date;

public class CreateBillFrm extends JFrame {
    private JPanel mainPanel;
    private JTextField ngàyThanhToánTextField;
    private JTextField họTênTextField;
    private JTextField sốĐiệnThoạiTextField;
    private JTextField phươngThứcThanhToánTextField;
    private JTextField txtClientPhone;
    private JTextField txtClientName;
    private JTextField txtPaymentDate;
    private JTable tblUsedServiceList;
    private JComboBox cbPaymentMethod;
    private JButton btnConfirm;
    private JButton btnCancel;
    private JTextField txtTotalAmount;
    private JTextField tổngTiềnTextField;
    private JTextArea txtNote;

    private DefaultTableModel tableModel;

    private ArrayList<Integer> selectedAppointmentIds;
    private float totalBillAmount = 0;

    public CreateBillFrm(ArrayList<Integer> apptIds, String clientName, String clientPhone) {
        this.selectedAppointmentIds = apptIds;

        setTitle("Lập Hóa Đơn");
        setContentPane(mainPanel);
        setSize(800, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        txtClientName.setText(clientName);
        txtClientPhone.setText(clientPhone);
        txtPaymentDate.setText(new Date(System.currentTimeMillis()).toString()); // Ngày hôm nay

        txtClientName.setEditable(false);
        txtClientPhone.setEditable(false);
        txtPaymentDate.setEditable(false);
        txtTotalAmount.setEditable(false); // không thể sửa

        setupTable();
        loadUsedServices();

        btnConfirm.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (cbPaymentMethod.getSelectedItem() == null) {
                    JOptionPane.showMessageDialog(CreateBillFrm.this, "Vui lòng chọn phương thức thanh toán!");
                    return;
                }

                Bill bill = new Bill();
                bill.setPaymentDate(Date.valueOf(txtPaymentDate.getText()));
                bill.setPaymentAmount(totalBillAmount);
                bill.setPaymentMethod(cbPaymentMethod.getSelectedItem().toString());
                bill.setNote(txtNote.getText());

                BillDAO billDAO = new BillDAO();
                int newBillId = billDAO.createBill(bill);

                if (newBillId > 0) {
                    AppointmentDAO dao = new AppointmentDAO();
                    dao.updateStatus(selectedAppointmentIds, newBillId);

                    JOptionPane.showMessageDialog(CreateBillFrm.this, "Lập hóa đơn thành công!");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(CreateBillFrm.this, "Lỗi khi lưu hóa đơn!");
                }
            }
        });

        btnCancel.addActionListener(e -> dispose());
    }

    private void setupTable() {
        String[] cols = {"STT", "Tên dịch vụ", "Số lượng", "Đơn giá", "Thành tiền"};
        tableModel = new DefaultTableModel(cols, 0);
        tblUsedServiceList.setModel(tableModel);
    }

    private void loadUsedServices() {
        UsedServiceDAO dao = new UsedServiceDAO();
        ArrayList<UsedService> usedServices = dao.getUsedServicesByAppointmentIds(selectedAppointmentIds);

        int index = 1;
        totalBillAmount = 0;

        for (UsedService usedService : usedServices) {
            tableModel.addRow(new Object[]{
                    index++,
                    usedService.getServiceName(),
                    usedService.getQuantity(),
                    String.format("%,.0f", usedService.getPrice()),
                    String.format("%,.0f", usedService.getTotalAmount())
            });
            totalBillAmount += usedService.getTotalAmount();
        }
        txtTotalAmount.setText(String.format("%,.0f VND", totalBillAmount));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(8, 2, new Insets(0, 0, 0, 0), -1, -1));
        ngàyThanhToánTextField = new JTextField();
        ngàyThanhToánTextField.setText("Ngày thanh toán");
        mainPanel.add(ngàyThanhToánTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        sốĐiệnThoạiTextField = new JTextField();
        sốĐiệnThoạiTextField.setText("Số điện thoại");
        mainPanel.add(sốĐiệnThoạiTextField, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tblUsedServiceList = new JTable();
        scrollPane1.setViewportView(tblUsedServiceList);
        phươngThứcThanhToánTextField = new JTextField();
        phươngThứcThanhToánTextField.setText("Phương thức thanh toán");
        mainPanel.add(phươngThứcThanhToánTextField, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtClientPhone = new JTextField();
        mainPanel.add(txtClientPhone, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtClientName = new JTextField();
        mainPanel.add(txtClientName, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtPaymentDate = new JTextField();
        mainPanel.add(txtPaymentDate, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        họTênTextField = new JTextField();
        họTênTextField.setText("Họ tên");
        mainPanel.add(họTênTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cbPaymentMethod = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Tiền mặt");
        defaultComboBoxModel1.addElement("Chuyển khoản");
        defaultComboBoxModel1.addElement("Quẹt thẻ");
        cbPaymentMethod.setModel(defaultComboBoxModel1);
        mainPanel.add(cbPaymentMethod, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnConfirm = new JButton();
        btnConfirm.setText("Confirm");
        mainPanel.add(btnConfirm, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCancel = new JButton();
        btnCancel.setText("Cancel");
        mainPanel.add(btnCancel, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtTotalAmount = new JTextField();
        mainPanel.add(txtTotalAmount, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        tổngTiềnTextField = new JTextField();
        tổngTiềnTextField.setText("Tổng tiền");
        mainPanel.add(tổngTiềnTextField, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtNote = new JTextArea();
        txtNote.setText("Note:");
        mainPanel.add(txtNote, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
