// Code khung cơ bản cho PendingAppointmentFrm.java
package view;
import javax.swing.*;
import java.awt.*;

public class PendingAppointmentFrm extends JFrame {
    private JPanel mainPanel;

    public PendingAppointmentFrm() {
        setTitle("Tìm kiếm ca khám chờ thanh toán");
        setContentPane(mainPanel);
        setSize(800, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Tắt form này không tắt màn hình chính
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}