package view;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ReceptionistHomeFrm extends JFrame {
    private JPanel mainPanel;
    private JButton btnPayment; // Nút Thanh toán (Tra cứu ca khám)
    private JButton btnViewBills; // Nút Xem danh sách hóa đơn

    public ReceptionistHomeFrm() {
        setTitle("Hệ thống Quản lý Phòng Khám - Lễ Tân");
        setContentPane(mainPanel);
        setSize(500, 350);
        setLocationRelativeTo(null); // Căn giữa màn hình
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Đóng app khi tắt màn hình chính

        // 1. Chức năng Thanh toán -> Dẫn ra PendingAppointmentFrm
        btnPayment.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mở giao diện danh sách ca chờ thanh toán
                PendingAppointmentFrm pendingFrm = new PendingAppointmentFrm();
                pendingFrm.setVisible(true);
            }
        });

        // 2. Chức năng Xem danh sách hóa đơn -> Dẫn ra BillListFrm
        btnViewBills.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mở giao diện danh sách hóa đơn
                BillListFrm billListFrm = new BillListFrm();
                billListFrm.setVisible(true);
            }
        });
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new ReceptionistHomeFrm().setVisible(true);
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        btnPayment = new JButton();
        btnPayment.setText("Thanh toán");
        mainPanel.add(btnPayment, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnViewBills = new JButton();
        btnViewBills.setText("Danh sách hóa đơn");
        mainPanel.add(btnViewBills, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}